function [] = show_poly(id_t)
close all
%figure
global info_trace;
global trace_vertex;
global trace;
global node;
global triangle;
global edge
global n_edges
axes('XAxisLocation','origin','YAxisLocation','origin');
hold on;
axis equal;
%base grigia di tutta la triangolazione
for i=1:n_edges
    line([node(edge(i,1)).x node(edge(i,2)).x],...
         [node(edge(i,1)).y node(edge(i,2)).y],...
         'Color',[0.8 0.8 0.8]);
    hold on
end

%mostro traccia intera
plot([trace_vertex(trace(id_t,1),1) trace_vertex(trace(id_t,2),1)],...
     [trace_vertex(trace(id_t,1),2) trace_vertex(trace(id_t,2),2)],...
     '.-r','MarkerSize',9);
hold on

%mostro le intersezioni della traccia (rosso)
s=sort(info_trace(id_t).s);

for i=1:(length(s))
    plot(trace_vertex(trace(id_t,1),1)+s(i)*(trace_vertex(trace(id_t,2),1)-trace_vertex(trace(id_t,1),1)), ...
         trace_vertex(trace(id_t,1),2)+s(i)*(trace_vertex(trace(id_t,2),2)-trace_vertex(trace(id_t,1),2)), ...
         'Color','r','MarkerSize',5,'Marker','o');
    hold on;
end

%mostro i poligoni (azzurro)
if(info_trace(id_t).cut_tri(1).id~=0)
for i=1:length(info_trace(id_t).cut_tri)
    %primo poligono
    line([info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(1) ,1) ...
          info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(2) ,1) ...
          info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(3) ,1)], ...
         [info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(1) ,2) ...
          info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(2) ,2) ...
          info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(3) ,2)], ...
          'Color',[0.1 0.7 1]);
    hold on;
    if( info_trace(id_t).cut_tri(i).poly_1(4)==0)
        line([info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(3) ,1) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(1) ,1)], ...
             [info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(3) ,2) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(1) ,2)], ...
              'Color',[0.1 0.7 1]);
        hold on;
    else
        line([info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(3) ,1) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(4) ,1) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(1) ,1)], ...
             [info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(3) ,2) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(4) ,2) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_1(1) ,2)], ...
              'Color',[0.1 0.7 1]);
        hold on;
    end
    
    %secondo poligono
    if(~isempty(info_trace(id_t).cut_tri(i).poly_2))
        line([info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_2(1) ,1) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_2(2) ,1) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_2(3) ,1) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_2(1) ,1)], ...
             [info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_2(1) ,2) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_2(2) ,2) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_2(3) ,2) ...
              info_trace(id_t).cut_tri(i).points( info_trace(id_t).cut_tri(i).poly_2(1) ,2)], ...
              'Color',[0.1 0.7 1]);
        hold on;
        
    end
    
    
end

%mostro i triangoli originari (blu scuro)
% for i=1:length(info_trace(id_t).cut_tri)
%     for j=1:3
%         line(node(triangle( info_trace(id_t).cut_tri(i).id ,j)).x, ...
%              node(triangle( info_trace(id_t).cut_tri(i).id ,j)).y, ...
%              'Color',[0 0 0.5],'Marker','.','MarkerSize',8);
%         hold on;
%         
%     end
% end
for i=1:length(info_trace(id_t).cut_tri)
    fill([node(triangle(info_trace(id_t).cut_tri(i).id,1)).x ...
          node(triangle(info_trace(id_t).cut_tri(i).id,2)).x ...
          node(triangle(info_trace(id_t).cut_tri(i).id,3)).x], ...
         [node(triangle(info_trace(id_t).cut_tri(i).id,1)).y ...
          node(triangle(info_trace(id_t).cut_tri(i).id,2)).y ...
          node(triangle(info_trace(id_t).cut_tri(i).id,3)).y], ...
         [0 0.2 0.6],'FaceAlpha',0.1,'EdgeAlpha',0);
     hold on;
end
end

end

